### ISSUE TITLE
Unable to reproduce paper results

### ISSUE THREAD

**Issue by johan-gras** [chancefocus/PIXIU#16] opened 2023-08-15 21:50 UTC
Hello,

I tried to reproduce the results from the paper, but I have a mismatch.

This is my cmd:
```bash
python eval.py \
    --model "hf-causal-llama" \
    --model_args "pretrained=chancefocus/finma-7b-full,tokenizer=chancefocus/finma-7b-full,use_fast=False" \
    --tasks "..."
```

The results:
```
|  Task   |Version| Metric |Value |   |Stderr|
|---------|------:|--------|-----:|---|-----:|
|flare_fpb|      1|acc     |0.9392|±  |0.0077|
|         |       |missing |0.0000|±  |0.0000|
|         |       |f1      |0.9393|   |      |
|         |       |macro_f1|0.9351|   |      |

|    Task    |Version| Metric |Value |   |Stderr|
|------------|------:|--------|-----:|---|-----:|
|flare_fiqasa|      1|acc     |0.8298|±  |0.0246|
|            |       |missing |0.0000|±  |0.0000|
|            |       |f1      |0.8294|   |      |
|            |       |macro_f1|0.7050|   |      |

|     Task      |Version|Metric|Value |   |Stderr|
|---------------|------:|------|-----:|---|------|
|flare_headlines|      1|avg_f1|0.9582|   |      |


|  Task   |Version| Metric  |Value |   |Stderr|
|---------|------:|---------|-----:|---|------|
|flare_ner|      1|entity_f1|0.5429|   |      |

|   Task    |Version|Metric|Value |   |Stderr|
|-----------|------:|------|-----:|---|-----:|
|flare_finqa|      1|acc   |0.0724|±  |0.0077|

|      Task      |Version| Metric |Value |   |Stderr|
|----------------|------:|--------|-----:|---|-----:|
|flare_sm_bigdata|      1|acc     |0.5054|±  |0.0130|
|                |       |missing |0.0000|±  |0.0000|
|                |       |f1      |0.5042|   |      |
|                |       |macro_f1|0.5048|   |      |
|                |       |mcc     |0.0145|±  |0.0273|

|    Task    |Version| Metric |Value |   |Stderr|
|------------|------:|--------|-----:|---|-----:|
|flare_sm_acl|      1|acc     |0.4782|±  |0.0082|
|            |       |missing |0.0699|±  |0.0042|
|            |       |f1      |0.4957|   |      |
|            |       |macro_f1|0.4955|   |      |
|            |       |mcc     |0.0257|±  |0.0146|

|    Task     |Version| Metric |Value |   |Stderr|
|-------------|------:|--------|-----:|---|-----:|
|flare_sm_cikm|      1|acc     |0.3246|±  |0.0139|
|             |       |missing |0.3631|±  |0.0142|
|             |       |f1      |0.4048|   |      |
|             |       |macro_f1|0.3962|   |      |
|             |       |mcc     |0.0374|±  |0.0215|
```

Also for ConvFinQA I get this error:
```
File "/nfs/home/johang/PIXIU/src/eval.py", line 98, in <module>
    main()
  File "/nfs/home/johang/PIXIU/src/eval.py", line 63, in main
    results = evaluator.simple_evaluate(
  File "/nfs/home/johang/PIXIU/src/financial-evaluation/lm_eval/utils.py", line 243, in _wrapper
    return fn(*args, **kwargs)
  File "/nfs/home/johang/PIXIU/src/evaluator.py", line 102, in simple_evaluate
    results = evaluate(
  File "/nfs/home/johang/PIXIU/src/financial-evaluation/lm_eval/utils.py", line 243, in _wrapper
    return fn(*args, **kwargs)
  File "/nfs/home/johang/PIXIU/src/evaluator.py", line 327, in evaluate
    resps = getattr(lm, reqtype)([req.args for req in reqs])
  File "/nfs/home/johang/PIXIU/src/financial-evaluation/lm_eval/base.py", line 922, in fn
    rem_res = getattr(self.lm, attr)(remaining_reqs)
  File "/nfs/home/johang/PIXIU/src/financial-evaluation/lm_eval/models/huggingface.py", line 473, in greedy_until
    request_args = chunk[0][1]
IndexError: list index out of range
```

What command should I run to get the same results as in the paper?
Thanks.

**Comment by jiminHuang** [comment] 2023-08-15 22:53
Hello,

Thank you for your interest and effort in reproducing the results from our paper. The results you're obtaining might differ from the paper due to the way the evaluations are conducted. The results presented in the original PIXIU paper were obtained through self-hosted evaluations, which can sometimes vary from automatic evaluations that are still under development. Our self-hosted evaluation approach involves running inference backends and adjusting the interface script according to your environment requirements.

To run the inference backend, you can use the following command:

```bash
bash scripts/run_interface.sh
```
After setting up the inference backend, you can evaluate the model using the provided evaluation scripts:

```bash
python data/*/evaluate.py
```
It's important to note that the results obtained from self-hosted evaluations might show slight variations due to the probabilistic nature of LLMs. However, these variations should still be generally consistent with the results presented in the paper.

**Comment by tothemoon96** [comment] 2023-08-16 01:28
please add "--model_prompt finma_prompt"

**Comment by johan-gras** [comment] 2023-08-21 23:05
Thank you both!

I understand that if I want to reproduce the results from the paper, I need to use the correct inference backend. However, would you say that it makes more sense to use the automatic evaluations, or is it not mature enough yet?

@tothemoon96 , when using the finma_prompt, I have something like "Human: [...] Answer:\nAssistant:". Don't you think that the "Answer:" is redundant?

**Comment by jiminHuang** [comment] 2023-08-21 23:17
@johan-gras Good question!

We are actively working on refining our new automated evaluation framework to align it closely with results from the traditional inference backend. While we acknowledge that the two methods might yield different results due to different generation and evaluation methods, we strongly believe that our new automatic evaluation provides a level of convenience and efficiency that the traditional method cannot offer.

Because of these advantages, and to make the research more accessible and reproducible, we have decided to update the results in our upcoming paper to those obtained using our new automated evaluation framework. Unfortunately, due to the paper being under review, we can't currently update our arXiv version.

We're quite excited to share that the first stable version of this framework will be released soon, along with the inclusion of more than 15 new datasets for a diversified assessment. We expect to roll out these updates within the next two weeks.

Given these developments, we would recommend waiting for the release of our stable automated evaluation framework for the most up-to-date and streamlined experience.

We hope you'll find this forthcoming release as exciting as we do. Please stay tuned for further updates!

**Closed** 2023-10-13 23:14 UTC
Labels: help wanted
